apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      # volumes:
      # - name: mongo
      #   persistentVolumeClaim:
      #     claimName: mongo-pvc
      containers:
      - name: mongo
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
        # volumeMounts:
        # - name: mongo
        #   mountPath: /data/db
        env:
          - name: MONGO_INITDB_DATABASE
            value: admin
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017